"""Tests for utils/ass_parser.py."""

import os
import tempfile
import unittest

from utils.ass_parser import (
    parse_ass,
    write_ass,
    extract_dialogue_lines,
    timestamp_to_seconds,
    seconds_to_timestamp,
)


SAMPLE_ASS = """\
[Script Info]
; Script generated by Aegisub 3.4.2
Title: Test File
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Speaker1,Arial,48,&H00FFFFFF,&H000000FF,&H00FF0000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:05.00,0:00:08.00,Default,,0,0,0,,Hello everyone!
Comment: 0,0:00:08.00,0:00:09.00,Default,,0,0,0,,This is a comment
Dialogue: 0,0:00:09.00,0:00:12.50,Speaker1,,0,0,0,,Nice to meet you.
Dialogue: 0,0:00:12.50,0:00:15.00,Default,,0,0,0,,Text with commas, and more, commas here
"""


class TestTimestampConversion(unittest.TestCase):
    def test_basic(self):
        self.assertAlmostEqual(timestamp_to_seconds("0:00:05.00"), 5.0)
        self.assertAlmostEqual(timestamp_to_seconds("0:01:30.50"), 90.5)
        self.assertAlmostEqual(timestamp_to_seconds("1:00:00.00"), 3600.0)

    def test_centiseconds(self):
        self.assertAlmostEqual(timestamp_to_seconds("0:00:01.25"), 1.25)
        self.assertAlmostEqual(timestamp_to_seconds("0:00:00.99"), 0.99)

    def test_roundtrip(self):
        for val in [0.0, 5.0, 90.5, 3600.0, 1.25]:
            self.assertEqual(timestamp_to_seconds(seconds_to_timestamp(val)), val)


class TestParseAss(unittest.TestCase):
    def setUp(self):
        self.tmpfile = tempfile.NamedTemporaryFile(
            mode="w", suffix=".ass", delete=False, encoding="utf-8"
        )
        self.tmpfile.write(SAMPLE_ASS)
        self.tmpfile.close()

    def tearDown(self):
        os.unlink(self.tmpfile.name)

    def test_script_info(self):
        data = parse_ass(self.tmpfile.name)
        self.assertIn("Test File", data["script_info"])
        self.assertIn("ScriptType: v4.00+", data["script_info"])

    def test_styles_parsed(self):
        data = parse_ass(self.tmpfile.name)
        self.assertEqual(len(data["styles"]), 2)
        self.assertIn("Default", data["styles"][0])
        self.assertIn("Speaker1", data["styles"][1])

    def test_events_parsed(self):
        data = parse_ass(self.tmpfile.name)
        self.assertEqual(len(data["events"]), 4)

    def test_dialogue_fields(self):
        data = parse_ass(self.tmpfile.name)
        first = data["events"][0]
        self.assertEqual(first["type"], "Dialogue")
        self.assertEqual(first["layer"], 0)
        self.assertEqual(first["start"], "0:00:05.00")
        self.assertEqual(first["end"], "0:00:08.00")
        self.assertEqual(first["style"], "Default")
        self.assertEqual(first["text"], "Hello everyone!")

    def test_comment_preserved(self):
        data = parse_ass(self.tmpfile.name)
        comment = data["events"][1]
        self.assertEqual(comment["type"], "Comment")
        self.assertEqual(comment["text"], "This is a comment")

    def test_text_with_commas(self):
        data = parse_ass(self.tmpfile.name)
        last = data["events"][3]
        self.assertEqual(last["text"], "Text with commas, and more, commas here")

    def test_styles_header(self):
        data = parse_ass(self.tmpfile.name)
        self.assertIn("Format:", data["styles_header"])

    def test_events_header(self):
        data = parse_ass(self.tmpfile.name)
        self.assertIn("Format:", data["events_header"])


class TestWriteAss(unittest.TestCase):
    def setUp(self):
        self.tmpfile = tempfile.NamedTemporaryFile(
            mode="w", suffix=".ass", delete=False, encoding="utf-8"
        )
        self.tmpfile.write(SAMPLE_ASS)
        self.tmpfile.close()

    def tearDown(self):
        os.unlink(self.tmpfile.name)
        if os.path.exists(self.tmpfile.name + ".out"):
            os.unlink(self.tmpfile.name + ".out")

    def test_roundtrip_events(self):
        """Parse -> write -> parse produces the same events."""
        data = parse_ass(self.tmpfile.name)
        out_path = self.tmpfile.name + ".out"
        write_ass(data, out_path)
        data2 = parse_ass(out_path)

        self.assertEqual(len(data["events"]), len(data2["events"]))
        for e1, e2 in zip(data["events"], data2["events"]):
            self.assertEqual(e1["type"], e2["type"])
            self.assertEqual(e1["start"], e2["start"])
            self.assertEqual(e1["end"], e2["end"])
            self.assertEqual(e1["style"], e2["style"])
            self.assertEqual(e1["text"], e2["text"])

    def test_roundtrip_styles(self):
        data = parse_ass(self.tmpfile.name)
        out_path = self.tmpfile.name + ".out"
        write_ass(data, out_path)
        data2 = parse_ass(out_path)
        self.assertEqual(len(data["styles"]), len(data2["styles"]))


class TestExtractDialogueLines(unittest.TestCase):
    def setUp(self):
        self.tmpfile = tempfile.NamedTemporaryFile(
            mode="w", suffix=".ass", delete=False, encoding="utf-8"
        )
        self.tmpfile.write(SAMPLE_ASS)
        self.tmpfile.close()

    def tearDown(self):
        os.unlink(self.tmpfile.name)

    def test_excludes_comments(self):
        data = parse_ass(self.tmpfile.name)
        lines = extract_dialogue_lines(data["events"])
        # 4 events total, 1 is a Comment -> 3 Dialogue lines
        self.assertEqual(len(lines), 3)

    def test_timing_as_floats(self):
        data = parse_ass(self.tmpfile.name)
        lines = extract_dialogue_lines(data["events"])
        self.assertAlmostEqual(lines[0]["start"], 5.0)
        self.assertAlmostEqual(lines[0]["end"], 8.0)

    def test_has_required_keys(self):
        data = parse_ass(self.tmpfile.name)
        lines = extract_dialogue_lines(data["events"])
        for line in lines:
            self.assertIn("start", line)
            self.assertIn("end", line)
            self.assertIn("style", line)
            self.assertIn("text", line)


class TestParseRealFile(unittest.TestCase):
    """Test parsing a real Lieraji ASS file if available."""

    REAL_FILE = "projects/Lieraji/Episode 249/Ep 249.ass"

    def setUp(self):
        self.skip = not os.path.exists(self.REAL_FILE)
        if self.skip:
            self.skipTest(f"Real file not found: {self.REAL_FILE}")

    def test_parse_real_file(self):
        data = parse_ass(self.REAL_FILE)
        self.assertGreater(len(data["events"]), 0)
        self.assertGreater(len(data["styles"]), 0)

    def test_roundtrip_real_file(self):
        data = parse_ass(self.REAL_FILE)
        out_path = tempfile.mktemp(suffix=".ass")
        try:
            write_ass(data, out_path)
            data2 = parse_ass(out_path)
            self.assertEqual(len(data["events"]), len(data2["events"]))
            for e1, e2 in zip(data["events"], data2["events"]):
                self.assertEqual(e1["type"], e2["type"])
                self.assertEqual(e1["start"], e2["start"])
                self.assertEqual(e1["end"], e2["end"])
                self.assertEqual(e1["style"], e2["style"])
                self.assertEqual(e1["text"], e2["text"])
        finally:
            if os.path.exists(out_path):
                os.unlink(out_path)


if __name__ == "__main__":
    unittest.main()
